# Schema for the configuration files of the Drupal Business theme.
drupal_business.settings:
  type: theme_settings
  label: 'Drupal Business settings'
  mapping:
    font_size:
      type: integer
      label: Font size
